modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-3.0"

[[mods]]

modId = "dreamdisplayx"
version = "${version}"
displayName = "Dream DisplaysX"
logoFile = "assets/dreamdisplayx/icon.png"
authors = "Baymaxawa, arnodoelinger, INotSleep, Kolyakot33, Toffikk"
description = "Create in-game screens to stream videos on any Minecraft server."

[[mixins]]
config = "dreamdisplayx.mixins.json"

[[mixins]]
config = "dreamdisplayx.server.mixins.json"

[[dependencies.dreamdisplayx]]
modId = "neoforge"
type = "required"
versionRange = "${neoforgeLoaderRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.dreamdisplayx]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.dreamdisplayx]]
modId = "luckperms"
type = "optional"
versionRange = "[5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dreamdisplayx]]
modId = "lambdynlights"
type = "optional"
versionRange = "[4,)"
ordering = "AFTER"
side = "CLIENT"
