name: DreamDisplaysX
version: '${version}'
main: com.dreamdisplayx.platform.server.PaperServer
api-version: '${paperMinecraftApi}'
description: 'Plugin for the Dream DisplaysX mod.'
authors:
  - Baymaxawa
  - arnodoelinger
  - INotSleep
  - Kolyakot33
  - Toffikk
folia-supported: true
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true
    GriefPrevention:
      load: BEFORE
      required: false
      join-classpath: true
    Residence:
      load: BEFORE
      required: false
      join-classpath: true
    Lands:
      load: BEFORE
      required: false
      join-classpath: true
    Towny:
      load: BEFORE
      required: false
      join-classpath: true
permissions:
  dreamdisplayx.create:
    default: true
  dreamdisplayx.video:
    default: true
  dreamdisplayx.info:
    default: true
  dreamdisplayx.help:
    default: true
  dreamdisplayx.local:
    default: true
  dreamdisplayx.synced:
    default: true
  dreamdisplayx.broadcast:
    default: true
  dreamdisplayx.watchparty:
    default: true
  dreamdisplayx.custom:
    default: true
  dreamdisplayx.lock:
    default: true
  dreamdisplayx.delete:
    default: true
  dreamdisplayx.delete.others:
    default: op
  dreamdisplayx.list:
    default: op
  dreamdisplayx.stats:
    default: op
  dreamdisplayx.premium:
    default: op
  dreamdisplayx.reload:
    default: op
  dreamdisplayx.updates:
    default: op
  dreamdisplayx.toggle.others:
    default: op
  dreamdisplayx.create.bypass:
    default: op
  dreamdisplayx.fullscreen.start:
    default: op
  dreamdisplayx.fullscreen.stop:
    default: op
  dreamdisplayx.fullscreen.list:
    default: op
  dreamdisplayx.fullscreen.network:
    default: op
  dreamdisplayx.remote:
    default: op
  dreamdisplayx.name:
    default: true
  dreamdisplayx.name.others:
    default: op
  dreamdisplayx.schedule:
    default: true
  dreamdisplayx.schedule.others:
    default: op
