package com.dreamdisplayx.platform.client.render

import kotlin.math.PI
import kotlin.math.ceil
import kotlin.math.cos
import kotlin.math.min
import kotlin.math.sin

/** Pure, time-based choreography; coordinates are normalized with the origin at the top left. */
internal object LoadingScreenAnimation {
    const val ICON_FADE_MS = 500.0
    const val SLIDE_START_MS = 650.0
    const val SLIDE_END_MS = 1300.0
    const val SPINNER_START_MS = 1450.0
    const val SPINNER_FADE_MS = 220.0
    const val WAVE_PERIOD_MS = 2600.0
    const val COLOR_PERIOD_MS = 8000.0
    const val SPINNER_PERIOD_MS = 1600.0
    const val BACKGROUND_RGB = 0x0B0E17

    private const val ICON_SIZE = 88f
    private const val GAP = 20f
    private const val TITLE_WIDTH = 268f
    private const val TITLE_HEIGHT = TITLE_WIDTH * 96f / 618f
    private const val GROUP_WIDTH = ICON_SIZE + GAP + TITLE_WIDTH
    private const val WAVE_HEIGHT = 2.5f
    private const val RING_RADIUS = 10f
    private const val BRUSH_SIZE = 2.8f

    // Atlas cells for "Dream DisplaysX", generated by scripts/generate_loading_assets.ps1.
    private val GLYPH_WIDTHS = intArrayOf(56, 31, 43, 42, 68, 24, 56, 23, 36, 48, 23, 42, 41, 36, 49)

    data class Rect(val x: Float, val y: Float, val width: Float, val height: Float) {
        val centerX: Float get() = x + width / 2f
        val centerY: Float get() = y + height / 2f
        val right: Float get() = x + width
        val bottom: Float get() = y + height
    }

    data class Glyph(val rect: Rect, val u0: Float, val u1: Float, val leftRgb: Int, val rightRgb: Int)
    data class Frame(
        val icon: Rect,
        val iconAlpha: Float,
        val title: Rect,
        val titleAlpha: Float,
        val glyphs: List<Glyph>,
        val spinner: Rect,
        val spinnerAlpha: Float,
        val ringBrushes: List<Rect>,
    )

    /** Fits the whole lockup uniformly: icons and rings remain round even on portrait displays. */
    fun frame(elapsedNanos: Long, width: Int, height: Int): Frame {
        val ms = elapsedNanos.coerceAtLeast(0L) / 1_000_000.0
        val w = width.coerceAtLeast(1).toFloat()
        val h = height.coerceAtLeast(1).toFloat()
        val scale = min(w * 0.78f / GROUP_WIDTH, h / 360f)
        val sx = scale / w
        val sy = scale / h
        val fade = ease(ms / ICON_FADE_MS)
        val slide = ease((ms - SLIDE_START_MS) / (SLIDE_END_MS - SLIDE_START_MS))
        val spinnerAlpha = ease((ms - SPINNER_START_MS) / SPINNER_FADE_MS)
        val left = 0.5f - GROUP_WIDTH * sx / 2f
        val iconEndX = left + ICON_SIZE * sx / 2f
        val iconCenterX = 0.5f + (iconEndX - 0.5f) * slide
        val icon = Rect(iconCenterX - ICON_SIZE * sx / 2f, 0.5f - ICON_SIZE * sy / 2f, ICON_SIZE * sx, ICON_SIZE * sy)
        val title = Rect(left + (ICON_SIZE + GAP) * sx, 0.5f - TITLE_HEIGHT * sy / 2f, TITLE_WIDTH * sx, TITLE_HEIGHT * sy)
        val wavePhase = ((ms - SLIDE_START_MS).coerceAtLeast(0.0) % WAVE_PERIOD_MS) / WAVE_PERIOD_MS * PI * 2
        val colorPhase = ((ms % COLOR_PERIOD_MS) / COLOR_PERIOD_MS).toFloat()
        var column = 0
        val glyphs = GLYPH_WIDTHS.indices.mapNotNull { index ->
            val pixels = GLYPH_WIDTHS[index]
            val u0 = column / 618f
            column += pixels
            val u1 = column / 618f
            if (index == 5) return@mapNotNull null // Keep the space's advance, not a transparent draw.
            val wave = sin(wavePhase - (u0 + u1) * PI).toFloat() * WAVE_HEIGHT * slide
            val glyph = Rect(
                title.x + title.width * u0,
                title.y + (18f * (1f - slide) + wave) * sy,
                title.width * (u1 - u0), title.height,
            )
            Glyph(glyph, u0, u1, rainbow(u0, colorPhase), rainbow(u1, colorPhase))
        }
        val spinnerCenterY = title.bottom + 20f * sy
        val spinner = Rect(title.centerX - RING_RADIUS * sx, spinnerCenterY - RING_RADIUS * sy, RING_RADIUS * 2f * sx, RING_RADIUS * 2f * sy)
        val brushes = if (spinnerAlpha > 0f) {
            // Windows 11-style continuous clockwise arc: the leading end runs ahead, then the tail catches up.
            val phase = ((ms - SPINNER_START_MS) % SPINNER_PERIOD_MS) / SPINNER_PERIOD_MS
            val sweep = (45.0 + 245.0 * (1.0 - cos(phase * PI * 2)) / 2.0) * PI / 180.0
            val head = phase * PI * 4 - PI / 2
            val steps = ceil(sweep * RING_RADIUS / 0.65).toInt().coerceAtLeast(1)
            (0..steps).map { step ->
                val angle = head - sweep + sweep * step / steps
                Rect(
                    spinner.centerX + (cos(angle).toFloat() * RING_RADIUS - BRUSH_SIZE / 2f) * sx,
                    spinner.centerY + (sin(angle).toFloat() * RING_RADIUS - BRUSH_SIZE / 2f) * sy,
                    BRUSH_SIZE * sx, BRUSH_SIZE * sy,
                )
            }
        } else emptyList()
        return Frame(icon, fade, title, slide, glyphs, spinner, spinnerAlpha, brushes)
    }

    /** A spatial rainbow travelling left to right; wrapping the hue makes the time loop seamless. */
    internal fun rainbow(position: Float, phase: Float = 0f): Int {
        val hue = ((position.coerceIn(0f, 1f) * 0.82f - phase) % 1f + 1f) % 1f * 6f
        val sector = hue.toInt()
        val f = hue - sector
        val low = 0.28f
        val falling = 1f - 0.72f * f
        val rising = low + 0.72f * f
        val (r, g, b) = when (sector) {
            0 -> Triple(1f, rising, low)
            1 -> Triple(falling, 1f, low)
            2 -> Triple(low, 1f, rising)
            3 -> Triple(low, falling, 1f)
            4 -> Triple(rising, low, 1f)
            else -> Triple(1f, low, falling)
        }
        return ((r * 255).toInt() shl 16) or ((g * 255).toInt() shl 8) or (b * 255).toInt()
    }

    private fun ease(value: Double): Float {
        val t = value.coerceIn(0.0, 1.0).toFloat()
        return t * t * (3f - 2f * t)
    }
}

/** Pure surface conventions shared by the flat and wrapped loading draws. */
internal object LoadingScreenGeometry {
    const val CONTENT_LIFT = 0.01f

    /** Replay must clear the level pass's frontmost sprite before compositing alpha again. */
    fun backgroundLift(baseLift: Float, replay: Boolean): Float = baseLift + if (replay) CONTENT_LIFT else 0f

    /** Inverts ConformingMesh's video rotation into top-left physical display coordinates. */
    fun uprightUv(u: Float, v: Float, quarterTurns: Int): Pair<Float, Float> = when (quarterTurns) {
        1 -> 1f - v to u
        2 -> 1f - u to 1f - v
        3 -> v to 1f - u
        else -> u to v
    }
}

/** Per-display clock: no global phase, minimum wait, wall-clock dependency, or native-player calls. */
internal class LoadingScreenClock {
    private var generation: Long? = null
    private var startNanos = 0L
    private var lastElapsed = 0L

    fun elapsed(enabled: Boolean, ready: Boolean, error: Boolean, mediaGeneration: Long, nowNanos: Long, replay: Boolean = false): Long? {
        if (!enabled || ready || error) {
            generation = null
            return null
        }
        if (generation != mediaGeneration) {
            generation = mediaGeneration
            startNanos = nowNanos
            lastElapsed = 0L
        }
        // A shader replay repaints this frame, not a later point on the animation's trajectory.
        if (!replay) lastElapsed = (nowNanos - startNanos).coerceAtLeast(0L)
        return lastElapsed
    }
}
